# Generated by Django 2.2 on 2019-04-24 16:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('pub_date', models.DateField(default=django.utils.timezone.now)),
                ('videofile', models.FileField(null=True, upload_to='data/', verbose_name='')),
            ],
        ),
    ]
